---
# Playbook to gather and display facts via DRAC.
- hosts: all
  gather_facts: no
  vars_prompt:
    # Prompt for the DRAC password if not already defined. It may be provided
    # as a variable override using ansible-playbook -e.
    - name: drac_password
      prompt: Password to access DRACs
      when: drac_password is not defined
  roles:
    # Include the stackhpc.drac-facts role to make the drac_facts module
    # available.
    - role: stackhpc.drac-facts
  tasks:
    # The drac_facts module will set the following facts:
    # drac_bios_settings
    # drac_jobs
    # drac_unfinished_jobs
    # drac_raid_controllers
    # drac_physical_disks
    # drac_virtual_disks
    - name: Gather facts via DRAC
      local_action:
        module: drac_facts
        address: "{{ ironic.driver_info.drac_address|default(ironic.driver_info.ipmi_address) }}"
        username: "{{ ironic.driver_info.drac_username|default(ironic.driver_info.ipmi_username) }}"
        password: "{{ drac_password }}"

    - name: Show gathered facts about BIOS settings
      debug:
        var: drac_bios_settings

    - name: Show gathered facts about jobs
      debug:
        var: drac_jobs

    - name: Show gathered facts about unfinished jobs
      debug:
        var: drac_unfinished_jobs

    - name: Show gathered facts about RAID controllers
      debug:
        var: drac_raid_controllers

    - name: Show gathered facts about physical disks
      debug:
        var: drac_physical_disks

    - name: Show gathered facts about virtual disks
      debug:
        var: drac_virtual_disks
